version: 2

site_name: dropboxignore
site_description: dropboxignore documentation page
site_author: Panagiotis Simakis
site_url: https://dropboxignore.simakis.me

theme:
  name: material
  custom_dir: 'docs/overrides'
  logo: static/logo.png
  favicon: static/favicon.png
  palette:
    primary: blue
  features:
    - navigation.instant

markdown_extensions:
  - admonition
  - pymdownx.keys
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

repo_url: https://github.com/sp1thas/dropboxignore/

nav:
  - 'Installation': 'installation.md'
  - 'Get started': 'getting-started.md'
  - 'CLI': 'cli.md'
  - 'Dev notes':
      - Contributing: 'contributing.md'
      - Testing: 'testing.md'
  - About:
      - License: 'license.md'
