version: 2

site_name: dropboxignore
site_description: dropboxignore documentation page
site_author: Panagiotis Simakis

theme:
  name: material
  logo: static/logo.png
  favicon: static/favicon.png
  palette:
    primary: blue
  features:
    - navigation.instant

markdown_extensions:
  - admonition

repo_url: https://github.com/sp1thas/dropboxignore/

nav:
  - 'User Guide':
      - Installation: 'installation.md'
      - Usage: 'usage.md'
  - 'Developer Documentation':
      - Contributing: 'contributing.md'
      - Testing: 'testing.md'
  - About:
      - License: 'license.md'
