version: 2
site_name: dropboxignore
theme:
  name: readthedocs

docs_dir:
  mkdocs

markdown_extensions:
  - admonition
repo_url: https://github.com/sp1thas/dropboxignore/

nav:
#  - Home: 'index.md'
  - 'User Guide':
    - Installation: 'installation.md'
    - Usage: 'usage.md'
  - 'Developer Documentation':
    - Contributing: 'contributing.md'
    - Testing: 'testing.md'
  - About:
    - License: 'license.md'
