name: dropboxignore
base: core18
adopt-info: get-version
summary: It's all about the missing .dropboxignore file.
description: |
  Exclude files from dropbox using glob patterns and take advantage of existing .gitignore files.
  This is a simple shell script that can be used to ignore files from dropbox using glob patterns, .dropboxignore files and the already existing .gitignorefiles. The shell script uses this approach to ignore the matched files.
icon: icons/256.png
grade: stable
confinement: strict

architectures:
  - build-on: amd64
    run-on: amd64

  - build-on: i386
    run-on: i386

  - build-on: arm64
    run-on: arm64
    build-error: ignore

  - build-on: armhf
    run-on: armhf
    build-error: ignore

  - build-on: ppc64el
    run-on: ppc64el
    build-error: ignore

  - build-on: s390x
    run-on: s390x
    build-error: ignore

apps:
  dropboxignore:
    command: ./bin/dropboxignore.sh
    plugs:
      - home

parts:

  get-version:
    build-packages:
      - curl
    plugin: nil
    override-pull: |
      snapcraftctl pull
      snapcraftctl set-version "$(curl -sSL https://raw.githubusercontent.com/sp1thas/dropboxignore/master/bin/dropboxignore.sh | grep -oP '^VERSION=(.*)$' | sed -r 's/^VERSION=//')"

  main-part:
    stage-packages:
      - attr
    source-type: git
    source: https://github.com/sp1thas/dropboxignore.git
    plugin: dump
    organize:
      dropboxignore.sh: dropboxignore

