name: dropboxignore
base: core18
adopt-info: get-version
summary: It's all about the missing .dropboxignore file.
icon: icons/256.png
grade: stable
confinement: strict

architectures: [ amd64, i386 ]

apps:
  dropboxignore:
    command: bash $SNAP/opt/dropboxignore/bin/dropboxignore.sh
    plugs:
      - home

parts:

  get-version:
    build-packages:
      - curl
    plugin: nil
    override-pull: |
      snapcraftctl pull
      snapcraftctl set-version "$(curl -fsSL https://raw.githubusercontent.com/sp1thas/dropboxignore/master/VERSION.txt)"

  dropboxignore:
    stage-packages:
      - attr
    source-type: git
    source: https://github.com/sp1thas/dropboxignore.git
    plugin: dump
    organize:
      dropboxignore.sh: opt/dropboxignore/bin/dropboxignore.sh

