name: dropboxignore
base: core18
adopt-info: get-version
summary: It's all about the missing .dropboxignore file.
description: |
  Exclude files from dropbox using glob patterns and take advantage of existing .gitignore files.
  This is a simple shell script that can be used to ignore files from dropbox using glob patterns, .dropboxignore files and the already existing .gitignorefiles. The shell script uses this approach to ignore the matched files.
icon: icons/256.png
grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

architectures: [ amd64, i386 ]

apps:
  dropboxignore:
    command: bash $SNAP/opt/dropboxignore/bin/dropboxignore.sh

parts:

  get-version:
    build-packages:
      - curl
    plugin: nil
    override-pull: |
      snapcraftctl pull
      snapcraftctl set-version "$(curl -fsSL https://raw.githubusercontent.com/sp1thas/dropboxignore/master/VERSION.txt)"

  dropboxignore:
    stage-packages:
      - attr
    source-type: git
    source: https://github.com/sp1thas/dropboxignore.git
    plugin: dump
    organize:
      dropboxignore.sh: opt/dropboxignore/bin/dropboxignore.sh

