name: Shellcheck

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  shellcheck:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install os dependencies
        run: sudo apt update && sudo apt install shellcheck

      - name: Run shellcheck
        run: |
          shellcheck tests/*.bats
          shellcheck *.sh

      - name: Install bats extras
        run: |
          git clone https://github.com/bats-core/bats-assert.git libs/bats-assert
          git clone https://github.com/bats-core/bats-support.git libs/bats-support
          git clone https://github.com/bats-core/bats-file.git libs/bats-file

      - name: Install dropboxignore
        run: |
          sudo make install

      - name: Run tests
        run: make test
