name: Get stats every 5 minutes

on:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  stats:
    runs-on: ubuntu-latest

    steps:
      - name: Install os dependencies
        run: sudo apt update && sudo apt install curl jq git
      
      - name: Create stats file
        run: sh -c "$(curl -fsSL https://raw.githubusercontent.com/sp1thas/dropboxignore/feat/count-installations/utils/stats.sh)"
