name: Testing

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install os dependencies
        run: apt update && apt install attr

      - name: Install bats-core
        run: |
          git clone https://github.com/bats-core/bats-core.git
          cd bats-core
          ./install.sh /usr/local

      - name: Install bats extras
        run: |
          git clone https://github.com/bats-core/bats-assert.git test/libs/bats-assert
          git clone https://github.com/bats-core/bats-support.git test/libs/bats-support
          git clone https://github.com/bats-core/bats-file.git test/libs/bats-file

      - name: Install dropboxignore
        run: |
          cp dropboxignore.sh /usr/local/bin/dropboxignore
          chmod +x /usr/local/bin/dropboxignore

      - name: Run tests
        run: dropboxignore version
